import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const out=path.join(root,"dist","client");const failures=[];const files=[];
const walk=(dir)=>{for(const entry of readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())walk(full);else if(entry.name.endsWith(".html"))files.push(full);}};
const check=(ok,message)=>{if(!ok)failures.push(message);};
const target=(href)=>{const clean=href.split("#")[0].split("?")[0];if(!clean||!clean.startsWith("/"))return null;if(clean==="/")return path.join(out,"index.html");if(path.extname(clean))return path.join(out,clean);return path.join(out,clean,"index.html");};
walk(out);const canonicals=new Map();for(const file of files){const rel=path.relative(out,file).replaceAll("\\","/");const html=readFileSync(file,"utf8");const title=html.match(/<title>(.*?)<\/title>/i)?.[1]?.trim();const desc=html.match(/<meta name="description" content="([^"]+)"/i)?.[1]?.trim();const canonical=html.match(/<link rel="canonical" href="([^"]+)"/i)?.[1];const h1=(html.match(/<h1(?:\s|>)/gi)??[]).length;check(Boolean(title),`${rel}: missing title`);check(Boolean(desc)&&desc.length>=70&&desc.length<=180,`${rel}: description length`);check(Boolean(canonical?.startsWith("https://yolloai.fun/")),`${rel}: canonical`);check(h1===1,`${rel}: expected one h1, got ${h1}`);check(/<meta name="robots"/i.test(html),`${rel}: robots`);check(/<meta property="og:image"/i.test(html),`${rel}: Open Graph`);if(canonical){check(!canonicals.has(canonical),`${rel}: duplicate canonical`);canonicals.set(canonical,rel);}for(const img of html.match(/<img\b[^>]*>/gi)??[])check(/\salt="[^"]+"/i.test(img),`${rel}: image alt`);for(const match of html.matchAll(/href="([^"]+)"/gi)){const item=target(match[1]);if(item)check(existsSync(item),`${rel}: broken ${match[1]}`);}}
check(existsSync(path.join(out,"robots.txt")),"missing robots.txt");check(existsSync(path.join(out,"sitemap-index.xml")),"missing sitemap");check(existsSync(path.join(out,"rss.xml")),"missing rss");check(existsSync(path.join(out,"29e6685c404b4754b70a6c97242af8be.txt")),"missing IndexNow key");
if(failures.length){console.error(`SEO audit failed:\n- ${failures.join("\n- ")}`);process.exit(1);}console.log(`SEO audit passed for ${files.length} HTML pages.`);

